### ISSUE TITLE
README.md: Debug build on Mac instead of release

### ISSUE THREAD

**Issue by CommonLoon102** [CommonLoon102/RegexFileSearcher#13]
The building process should create a binary what is built in release mode.
The README.md should be updated to publish the app on Mac instead of building it in debug mode.
Is it possible to build it on Mac in a similar way what we have now for Linux?

Something like this should work:
```
dotnet publish RegexFileSearcher/RegexFileSearcher.Mac/RegexFileSearcher.Mac.csproj --configuration Release --output publish --self-contained false --runtime osx-x64 --framework netcoreapp3.1
```

**Comment by CommonLoon102** [comment]
@adarke If you have time, could you have a look on this?

**Comment by adarke** [comment]
@CommonLoon102 Sure, no problem.

**Comment by n0-fun** [comment]
The commands could use a lot of abbreviations and simplification.
e.g. on Linux, it's as simple as:
```
$ # clone it
$ git clone https://github.com/CommonLoon102/RegexFileSearcher.git
$ # build it
$ cd RegexFileSearcher
$ dotnet build RegexFileSearcher/RegexFileSearcher.Gtk -c Release -o bin/ 
$ # run it
$ ./bin/RegexFileSearcher.Gtk 
```
On Windows, it's the same for the WPF project, but most users will prefer VS.
