### ISSUE TITLE
Using the program associated with the selected file(s) should be the default behaviour

### ISSUE THREAD

**Issue by n0-fun** [CommonLoon102/RegexFileSearcher#6]
Currently, the user has to manually pick an executable to launch the selected file(s).
This can be improved upon by applying the following when no editor is specified:

- Use `xdg-open` on Linux.
- Use `open` on macOS. 
- Use `start` on Windows.

All of the above are the standard ways of opening files using the associated program.

**Comment by n0-fun** [comment]
@CommonLoon102 I don't have a mac, so I left the macOS implementation commented out.
I am very certain it should work though, because I checked the dotnet repo and it looks like they are using `execve` on unix.
A quick google search shows that `open` is an executable under `/usr/bin` on macOS (just like `xdg-open` on Linux), which further confirms the  implementation correct.

**Comment by adarke** [comment]
> @CommonLoon102 I don't have a mac, so I left the macOS implementation commented out.
> I am very certain it should work though, because I checked the dotnet repo and it looks like they are using `execve` on unix.
> A quick google search shows that `open` is an executable under `/usr/bin` on macOS (just like `xdg-open` on Linux), which further confirms the implementation correct.
> Should I go ahead and uncomment it, or leave it as-is showing a message box when the user doesn't specify an editor on macOS?

Hi, 

I am testing on a Mac just now, I'll let you know how it goes.

**Comment by adarke** [comment]
Can confirm that implementation works on macOS, so lines can be uncommented.

**Comment by n0-fun** [comment]
@adarke Thanks for the update! Since you were just assigned, would you like to update the pull request with the suggested changes?

**Comment by adarke** [comment]
@n0-fun I don't have permissions to update the pull request for some reason, so would you mind making the changes?

**Comment by n0-fun** [comment]
@adarke Oh, I am not sure why that was the case. I _guess_ issue and pull request assignees and reviewers are entirely different things.
Anyways, I made the changes and the pull request should be ready for review now.

**Comment by CommonLoon102** [comment]
@n0-fun I've done some refactor on the code, please review, and if it is still fine, I can merge it.
