### ISSUE TITLE
Add an option for maximum file size limit

### ISSUE THREAD

**Issue by n0-fun** [CommonLoon102/RegexFileSearcher#7]
Regex operates on text, not binaries. As such, the current implementation simply reads the entire file into one string object.
While this approach avoids issues arising from buffered reading (such as a potential regex match getting cut-off), it poses a problem when a large file is encountered during file search.
This could be solved by allowing the user to specify a maximum file size, beyond which a file would be ignored.
A sane default, such as 5 MB would be preferred. See [discussion](https://github.com/CommonLoon102/RegexFileSearcher/pull/4#discussion_r470631636).

**Comment by CommonLoon102** [comment]
@n0-fun are you interested in this issue?

**Comment by n0-fun** [comment]
@CommonLoon102  Sorry, I didn't get any notification about the mention earlier.
The implementation is straightforward, but the design is not so much.
If you have a clear view of it, please go ahead. These are my attempts:
Under the filename regex:
![under](https://user-images.githubusercontent.com/68202390/90446468-1c4d0480-e0ea-11ea-85e3-e28c03a26cd7.jpg)
Replace the filename regex timeout:
![replace](https://user-images.githubusercontent.com/68202390/90446473-1fe08b80-e0ea-11ea-9947-55e1653024c3.jpg)

I don't think any of the supported OSes allow filenames (without path) longer than 510 bytes which means it's very very unlikely that a compiled regex will timeout on a filename.

**Comment by CommonLoon102** [comment]
> I don't think any of the supported OSes allow filenames (without path) longer than 510 bytes which means it's very very unlikely that a compiled regex will timeout on a filename.

There can be extreme edge cases when the regex will timeout, but maybe we could hard-code 5 seconds or something. In that case we could have the max file size setting instead of the regex timeout at the filename section.
